export interface MovieQuote {
  quote: string;
  movie: string;
  year: number;
}

/** A curated set of iconic movie lines shown around the app for flavor. */
export const MOVIE_QUOTES: MovieQuote[] = [
  { quote: "May the Force be with you.", movie: "Star Wars", year: 1977 },
  { quote: "Here's looking at you, kid.", movie: "Casablanca", year: 1942 },
  { quote: "Life is like a box of chocolates.", movie: "Forrest Gump", year: 1994 },
  { quote: "I'll be back.", movie: "The Terminator", year: 1984 },
  { quote: "Why so serious?", movie: "The Dark Knight", year: 2008 },
  { quote: "You're gonna need a bigger boat.", movie: "Jaws", year: 1975 },
  { quote: "There's no place like home.", movie: "The Wizard of Oz", year: 1939 },
  { quote: "I'm going to make him an offer he can't refuse.", movie: "The Godfather", year: 1972 },
  { quote: "Do or do not. There is no try.", movie: "The Empire Strikes Back", year: 1980 },
  { quote: "To infinity and beyond!", movie: "Toy Story", year: 1995 },
  { quote: "Just keep swimming.", movie: "Finding Nemo", year: 2003 },
  { quote: "I see dead people.", movie: "The Sixth Sense", year: 1999 },
  { quote: "You talking to me?", movie: "Taxi Driver", year: 1976 },
  { quote: "Roads? Where we're going we don't need roads.", movie: "Back to the Future", year: 1985 },
  { quote: "Hasta la vista, baby.", movie: "Terminator 2: Judgment Day", year: 1991 },
  { quote: "Say hello to my little friend!", movie: "Scarface", year: 1983 },
  { quote: "Nobody puts Baby in a corner.", movie: "Dirty Dancing", year: 1987 },
  { quote: "There is no spoon.", movie: "The Matrix", year: 1999 },
  { quote: "With great power comes great responsibility.", movie: "Spider-Man", year: 2002 },
  { quote: "Carpe diem. Seize the day, boys.", movie: "Dead Poets Society", year: 1989 },
  { quote: "E.T. phone home.", movie: "E.T. the Extra-Terrestrial", year: 1982 },
  { quote: "Frankly, my dear, I don't give a damn.", movie: "Gone with the Wind", year: 1939 },
  { quote: "Keep your friends close, but your enemies closer.", movie: "The Godfather Part II", year: 1974 },
  { quote: "They may take our lives, but they'll never take our freedom!", movie: "Braveheart", year: 1995 },
  { quote: "Houston, we have a problem.", movie: "Apollo 13", year: 1995 },
  { quote: "Wax on, wax off.", movie: "The Karate Kid", year: 1984 },
  { quote: "My precious.", movie: "The Lord of the Rings: The Two Towers", year: 2002 },
  { quote: "You can't handle the truth!", movie: "A Few Good Men", year: 1992 },
  { quote: "Here's Johnny!", movie: "The Shining", year: 1980 },
  { quote: "Toto, I've a feeling we're not in Kansas anymore.", movie: "The Wizard of Oz", year: 1939 },
  { quote: "I'm the king of the world!", movie: "Titanic", year: 1997 },
  { quote: "Elementary, my dear Watson.", movie: "The Adventures of Sherlock Holmes", year: 1939 },
  { quote: "You had me at hello.", movie: "Jerry Maguire", year: 1996 },
  { quote: "Show me the money!", movie: "Jerry Maguire", year: 1996 },
  { quote: "I feel the need — the need for speed!", movie: "Top Gun", year: 1986 },
  { quote: "They're here.", movie: "Poltergeist", year: 1982 },
  { quote: "Keep the change, ya filthy animal.", movie: "Home Alone", year: 1990 },
  { quote: "Why don't you knock it off with them negative waves?", movie: "Kelly's Heroes", year: 1970 },
  { quote: "Get to the choppa!", movie: "Predator", year: 1987 },
  { quote: "I am your father.", movie: "The Empire Strikes Back", year: 1980 },
  { quote: "You shall not pass!", movie: "The Lord of the Rings: The Fellowship of the Ring", year: 2001 },
  { quote: "One ring to rule them all.", movie: "The Lord of the Rings: The Fellowship of the Ring", year: 2001 },
  { quote: "After all this time? Always.", movie: "Harry Potter and the Deathly Hallows – Part 2", year: 2011 },
  { quote: "It's not who I am underneath, but what I do that defines me.", movie: "Batman Begins", year: 2005 },
  { quote: "Every man dies. Not every man really lives.", movie: "Braveheart", year: 1995 },
  { quote: "Why do we fall? So we can learn to pick ourselves up.", movie: "Batman Begins", year: 2005 },
  { quote: "Get busy living, or get busy dying.", movie: "The Shawshank Redemption", year: 1994 },
  { quote: "Hope is a good thing, maybe the best of things.", movie: "The Shawshank Redemption", year: 1994 },
  { quote: "The first rule of Fight Club is: you do not talk about Fight Club.", movie: "Fight Club", year: 1999 },
  { quote: "I drink your milkshake!", movie: "There Will Be Blood", year: 2007 },
  { quote: "You is kind. You is smart. You is important.", movie: "The Help", year: 2011 },
  { quote: "Great men are not born great, they grow great.", movie: "The Godfather", year: 1972 },
  { quote: "I'm walking here! I'm walking here!", movie: "Midnight Cowboy", year: 1969 },
  { quote: "Wilson!", movie: "Cast Away", year: 2000 },
  { quote: "Yippee-ki-yay.", movie: "Die Hard", year: 1988 },
  { quote: "As if!", movie: "Clueless", year: 1995 },
  { quote: "I'll have what she's having.", movie: "When Harry Met Sally...", year: 1989 },
  { quote: "You're killin' me, Smalls.", movie: "The Sandlot", year: 1993 },
  { quote: "To live would be an awfully big adventure.", movie: "Hook", year: 1991 },
  { quote: "Adventure is out there!", movie: "Up", year: 2009 },
  { quote: "Ohana means family. Family means nobody gets left behind.", movie: "Lilo & Stitch", year: 2002 },
  { quote: "Some people can't believe in themselves until someone else believes first.", movie: "Good Will Hunting", year: 1997 },
  { quote: "The greatest trick the devil ever pulled was convincing the world he didn't exist.", movie: "The Usual Suspects", year: 1995 },
  { quote: "Say what again. I dare you, I double dare you.", movie: "Pulp Fiction", year: 1994 },
  { quote: "Snap out of it!", movie: "Moonstruck", year: 1987 },
  { quote: "Life moves pretty fast. If you don't stop and look around once in a while, you could miss it.", movie: "Ferris Bueller's Day Off", year: 1986 },
  { quote: "Just when I thought I was out, they pull me back in.", movie: "The Godfather Part III", year: 1990 },
  { quote: "There's no crying in baseball!", movie: "A League of Their Own", year: 1992 },
  { quote: "Roll tide.", movie: "Crimson Tide", year: 1995 },
  { quote: "Inconceivable!", movie: "The Princess Bride", year: 1987 },
  { quote: "As you wish.", movie: "The Princess Bride", year: 1987 },
  { quote: "Have fun storming the castle!", movie: "The Princess Bride", year: 1987 },
  { quote: "That'll do, pig. That'll do.", movie: "Babe", year: 1995 },
  { quote: "I am Groot.", movie: "Guardians of the Galaxy", year: 2014 },
  { quote: "I can do this all day.", movie: "Captain America: The First Avenger", year: 2011 },
  { quote: "I love you 3000.", movie: "Avengers: Endgame", year: 2019 },
  { quote: "We're all mad here.", movie: "Alice in Wonderland", year: 1951 },
  { quote: "Fasten your seatbelts. It's going to be a bumpy night.", movie: "All About Eve", year: 1950 },
  { quote: "The stuff that dreams are made of.", movie: "The Maltese Falcon", year: 1941 },
  { quote: "Round up the usual suspects.", movie: "Casablanca", year: 1942 },
  { quote: "We'll always have Paris.", movie: "Casablanca", year: 1942 },
  { quote: "I'm as mad as hell, and I'm not going to take this anymore!", movie: "Network", year: 1976 },
  { quote: "You're only supposed to blow the bloody doors off!", movie: "The Italian Job", year: 1969 },
  { quote: "What we've got here is failure to communicate.", movie: "Cool Hand Luke", year: 1967 },
  { quote: "A boy's best friend is his mother.", movie: "Psycho", year: 1960 },
  { quote: "Made it, Ma! Top of the world!", movie: "White Heat", year: 1949 },
];

export function randomQuote(): MovieQuote {
  return MOVIE_QUOTES[Math.floor(Math.random() * MOVIE_QUOTES.length)];
}
